db:
  #build: postgres-gnuhealth
  image: informaticaglobal/postgres-gnuhealth:3.2
  volumes:
    - ./postgresql-data:/var/lib/postgresql/data
  environment:
    - POSTGRES_PASSWORD=mysecret

tryton:
  #build: tryton-server-gnuhealth
  image: informaticaglobal/tryton-server-gnuhealth:4.2
  volumes:
    - ./tryton-data:/var/lib/tryton
  environment:
    - TRYTOND_PASSWORD=admin
  ports:
    - "8000:8000"
  links:
    - db
